### PR TITLE
Add setup script for the project

### PR DESCRIPTION
**Pull request by Aniket21mathur**
@astatide @lydia-duncan @mppf

### CODE REVIEW

**Comment by astatide** [comment]
Hi Aniket!

This looks good, but it also looks like it's now included in the new PR.  I would recommend just closing this PR and merging the other PR when ready to avoid having to rebase.  Seems like it would just make it easier.

**Comment by lydia-duncan** [comment]
> I would recommend just closing this PR and merging the other PR when ready to avoid having to rebase. Seems like it would just make it easier.

When a PR that is a subset of another PR without diverging get merged, the larger PR then ends up reduced to only the new portions.  It won't require a rebase unless changes were made to the original branch

**Comment by Aniket21mathur** [comment]
Seems like the two branches have already diverged from 1fa6240 and 970be93. I don't know the exact reason why this happened, might be because of some force push and all. I see two possible ways from here ->
- One that @astatide suggested, to close this pr, add cherry-pick 2f420ad to the other pr(as it does not have this commit).
- Other to merge this pr, take a new branch out of master and cherry-pick all commits with required changes from the other pr to that branch and open a new pull request. The advantage of this will be that we will have all changes in order and it will be easier to revisit.

**Comment by mppf** [comment]
You can just rebase your other PR off of this PR (or master after it is merged)

`git rebase origin/master` 

See also https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#other-useful-information which describes some git strategies.

**Comment by Aniket21mathur** [comment]
> See also https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/ContributorInfo.rst#other-useful-information which describes some git strategies.

Thanks :)

So are we good to go with this pr?

**Comment by mppf** [comment]
Looks good to me.

**Pull request merged**
