### PR TITLE
Add support for serializing/deserializing `int64` and `int32` type

### PR DESCRIPTION
**Pull request by Aniket21mathur**
[File(https://github.com/Aniket21mathur/ProtocolBuffers/blob/master/chapel/integer/version/integer64v2.chpl) generated when [this](https://github.com/Aniket21mathur/ProtocolBuffers/blob/master/chapel/integer/integer64.proto) proto file is passed to the protoc compiler along with the chapel plugin.

**Note- The name of the output file is different, I renamed it after generation. The ideal file name will be integer64.chpl**

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@mppf @lydia-duncan @astatide can we get a quick review on this today? The functions in the `Protobuf.chpl` file have changed a lot in the new branches,  it would be better if we have a thorough review there. You guys can focus more on the C++ code in this pr, :)

**Review by mppf — APPROVED** [review]
So instead of generating the field type in the serialize/unserialize methods (encoded in which Dump call to make e.g.) you are getting the field type out of the wire protocol for the field? That seems OK to me and is probably more robust vs version changes in protobuf files. This seems like the main change to the C++ code and I wish the PR message talked about why you did this.

**Comment by Aniket21mathur** [comment]
> So instead of generating the field type in the serialize/unserialize methods (encoded in which Dump call to make e.g.) you are getting the field type out of the wire protocol for the field? That seems OK to me and is probably more robust vs version changes in protobuf files.

@mppf that works fine for now since we are dealing with integers only. But when we add more field types, we need to explicitly call dump/load function types. I have done those changes in [this](https://github.com/Aniket21mathur/Chapel-protobuf/commit/596d52ac693d2c975756ee30a075561b191be95d) commit from an updated branch. We cannot entirely distinguish fields using `wiretype` because some fields have same wiretype number but a bit different methods for encoding/decoding, for instance `int` and `sint` are both `varint` type but are encoded/decoded differently.

A generated file after the changes made in the above commit will look like [this](https://github.com/Aniket21mathur/ProtocolBuffers/blob/master/chapel/build/types.chpl)

**Comment by mppf** [comment]
@Aniket21mathur - sounds good

**Pull request merged**
